import { Metadata } from "next";
import { HelpCircle, ChevronDown, MessageCircle, Zap, Shield, CreditCard, Headphones } from "lucide-react";

export const metadata: Metadata = {
  title: "Frequently Asked Questions",
  description: "Common questions about ReplyBase features, pricing, and integrations.",
};

const faqs = [
  {
    category: "General",
    icon: HelpCircle,
    questions: [
      {
        q: "What is ReplyBase?",
        a: "ReplyBase is an AI-powered conversation automation platform that helps businesses capture leads and support customers across Webchat, WhatsApp, Telegram, and Facebook Messenger using advanced AI workflows."
      },
      {
        q: "Do I need coding skills to use ReplyBase?",
        a: "No. Most integrations like Facebook and Telegram are click-and-connect. Webchat requires copying a single line of code to your site. Advanced users can use our API and webhooks for deeper integrations."
      }
    ]
  },
  {
    category: "AI & Workflows",
    icon: Zap,
    questions: [
      {
        q: "How does the AI work?",
        a: "We use state-of-the-art LLMs (like GPT-4 and Gemini) to understand customer intent. You can configure 'Flows' to guide the conversation or let the AI respond dynamically based on your knowledge base."
      },
      {
        q: "Can I train the AI on my own data?",
        a: "Yes. You can upload documents or link your website in the 'Knowledge' section to ensure the AI provides accurate, business-specific information."
      }
    ]
  },
  {
    category: "Billing",
    icon: CreditCard,
    questions: [
      {
        q: "Is there a free plan?",
        a: "Yes! Our Free plan includes Webchat and Facebook Messenger with up to 100 AI messages per month. Perfect for testing and small businesses."
      },
      {
        q: "What counts as an 'AI Message'?",
        a: "Any response generated by the AI or an automated flow counts as one message. Human-to-human messages in the dashboard are always free."
      },
      {
        q: "Can I remove the 'Powered by ReplyBase' badge from my webchat widget?",
        a: "Yes. The badge appears automatically on Free and Launch (£29/mo) plans as a subtle footer link in the chat panel. Upgrading to the Grow plan (£49/mo) or above removes it entirely. Business plan subscribers can go further with full white-label branding — custom logo, colors, and email sender name — configured in Settings → Branding."
      }
    ]
  },
  {
    category: "Support & SLA",
    icon: Headphones,
    questions: [
      {
        q: "What support do I get on the Free plan?",
        a: "Free plan users have access to our community forum. There is no response-time commitment on the Free tier."
      },
      {
        q: "What is the response time on Launch and Grow plans?",
        a: "Launch and Grow subscribers receive Standard Email support with a best-effort 48-hour response target during business hours (9am–5pm GMT, Monday–Friday)."
      },
      {
        q: "What does 'Priority Email' mean on the Scale plan?",
        a: "Scale plan subscribers are placed in a priority queue with a 24-hour response target. Your tickets are reviewed before standard queue submissions."
      },
      {
        q: "What is Priority+ support on the Business plan?",
        a: "Business plan subscribers receive Priority+ support: a 4-hour response target during business hours, an optional dedicated Slack or WhatsApp support channel, and a quarterly business review call with the ReplyBase team."
      },
      {
        q: "How do I submit a Priority+ support ticket?",
        a: "Business plan subscribers can submit fast-track tickets directly from the platform via the Priority Support form in Settings → Billing. Tickets are routed to the Priority+ queue immediately."
      },
      {
        q: "Are response targets guaranteed 24/7?",
        a: "Response targets apply during business hours (9am–5pm GMT, Monday–Friday). Critical issues on the Business plan are reviewed on a best-effort basis outside these hours."
      }
    ]
  }
];

export default function FAQPage() {
  return (
    <div className="max-w-4xl">
      <div className="mb-12">
        <h1 className="text-4xl font-bold text-white mb-4">Frequently Asked Questions</h1>
        <p className="text-lg text-slate-400">Everything you need to know about the platform and how it works.</p>
      </div>

      <div className="space-y-12">
        {faqs.map((cat) => {
          const Icon = cat.icon;
          return (
            <section key={cat.category}>
              <div className="flex items-center gap-3 mb-6">
                <div className="flex items-center justify-center h-8 w-8 rounded-lg bg-indigo-600/20 text-indigo-400">
                  <Icon size={18} />
                </div>
                <h2 className="text-xl font-bold text-white">{cat.category}</h2>
              </div>
              <div className="space-y-4">
                {cat.questions.map((faq, idx) => (
                  <details 
                    key={idx} 
                    className="bg-slate-800/30 border border-slate-700 rounded-xl overflow-hidden group"
                  >
                    <summary className="p-5 cursor-pointer hover:bg-slate-800/50 transition-colors font-semibold text-white flex justify-between items-center list-none">
                      {faq.q}
                      <ChevronDown size={18} className="text-slate-500 group-open:rotate-180 transition-transform" />
                    </summary>
                    <div className="px-5 pb-5 text-slate-400 text-sm leading-relaxed">
                      {faq.a}
                    </div>
                  </details>
                ))}
              </div>
            </section>
          );
        })}
      </div>

      <div className="mt-20 p-8 bg-indigo-600/10 border border-indigo-500/20 rounded-2xl text-center">
        <h3 className="text-xl font-bold text-white mb-2">Still have questions?</h3>
        <p className="text-slate-400 mb-6">Our support team is available 9am-5pm GMT to help you with any queries.</p>
        <button className="px-8 py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg font-bold transition-colors">
          Contact Support
        </button>
      </div>
    </div>
  );
}
